apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-second.fullname" ( set . "Deployment" .Values.database ) }}
  labels:
    {{- include "quarkus-second.labels" ( set . "Deployment" .Values.database ) | nindent 4 }}
stringData:
  POSTGRES_PASSWORD: test
type: Opaque