apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarkus-second.database-fullname" . }}
  labels:
    {{- include "quarkus-second.database-labels" . | nindent 4 }}
stringData:
  POSTGRES_PASSWORD: test
type: Opaque