apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-second.fullname" ( set . "Deployment" .Values.restapp ) }}
  labels:
    {{- include "quarkus-second.labels" ( set . "Deployment" .Values.restapp ) | nindent 4 }}
spec:
  type: {{ .Values.restapp.service.type }}
  ports:
    - port: {{ .Values.restapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quarkus-second.selectorLabels" ( set . "Deployment" .Values.restapp ) | nindent 4 }}
