apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-second.restapp-fullname" . }}
  labels:
    {{- include "quarkus-second.restapp-labels" . | nindent 4 }}
spec:
  type: {{ .Values.restapp.service.type }}
  ports:
    - port: {{ .Values.restapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quarkus-second.restapp-selectorLabels" . | nindent 4 }}
